---
language: node_js
node_js:
  - "4"
  - "6"

dist: trusty
sudo: required

branches:
  only:
    - master
    - auto
    - /^greenkeeper.*$/

addons:
  chrome: stable

cache:
  yarn: true

env:
  - NPM_SCRIPT=node-test

matrix:
  fast_finish: true
  include:
  - node_js: "6"
    env: NPM_SCRIPT=lint:js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - npm run-script $NPM_SCRIPT
